### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by WhistleMaster** [polppol/openpollslack-i18n#22]
Hi,

Thanks for the great work ! It seems that the service is unavailable at the moment:

<img width="896" alt="Screenshot 2023-10-20 at 09 00 52" src="https://github.com/polppol/openpollslack-i18n/assets/1544568/fb7d3f23-725c-41a2-a4a9-4bc5534aaa1e">

Thanks !

**Comment by polppol** [comment]
Hi, Service might go under mantance for a few hours, if it still wont work for you please let me know your country/ISP as it might be in blocked list fot some reason.
