### ISSUE TITLE
Schedules and deleted poll keeps appearing

### ISSUE THREAD

**Issue by jvdmeij** [polppol/openpollslack-i18n#25]
First of all, thanks for building this. It's awesome!

I have an issue with a poll I scheduled a while back. It was planned to be posted every Friday. I deleted that one because I wanted to have it posted on a Thursday. The new poll is posted as it should on the new date. But the old poll is still showing up.

When using `/poll schedule list_all` I only see the poll that I expect there.

Is there any other way I can find and delete the unwanted poll? Is reinstalling the app an option? Thanks!

Ps it is a poll schedules for channel `C07TE8DK7FZ` if you want to find something on your end.

**Comment by polppol** [comment]
Hi,
Can I have you Poll ID: and Source ID: of poll that you didn't expect?
(click on menu of that poll > Command info)

**Comment by jvdmeij** [comment]
Thanks for the reply!

> Hi, From infomation you provided I only see one scheduled using cron "`00 13 * * 5`" which is friday to that channel (Source ID: `6751aadb2a37a95edbc90a58`)

Yes, that is the one I see to. 

The poll that was posted yesterday (Thursday) has pollId `675ae55a8e8161d47d6518e2`

> not sure if you delete incorrect scheduled? or you just accidentally delete message in slack it self without actually stop/delete schedule poll via `/poll schedule delete [POLL_ID]`?

I did (iirc) both.
 
> Can I have you Poll ID: and Source ID: of poll that you didn't expect? (click on menu of that poll > Command info)

I only have 2 Poll IDs from the ones that were posted last week, and that was `6752f5512a37a95edbc90b46`

**Comment by polppol** [comment]
Hi,
So first of all to stop this Recurring Poll from post next friday please use "/poll schedule delete 6751aadb2a37a95edbc90a58"
(this will not close or delete poll that already posted it just stop)

so, what happen here I think  you use this command to create your poll
`/poll schedule create [POLL_ID] [TS] [CH_ID] "[CRON_EXP]" [MAX_RUN]`
`/poll schedule create 6751aadb2a37a95edbc90a58 2024-12-12T15:30:00+02:00 C07TE8DK7FZ "00 13 * * 5"`
to breakdown this command:
- poll will posted once on 2024-12-12T15:30:00+02:00
- as you put  "00 13 * * 5" this poll will also post every friday @ 15:30:00+02:00 
- no [MAX_RUN], so it will keep posting every friday @ 15:30:00+02:00  for 365 times

If you want poll to post once you can use
command like this
`/poll on 2024-12-12T15:30:00+02:00 "What's your favourite color ?" "Red" "Green" "Blue" "Yellow"`

or if you want to repost/reuse previous create poll
`/poll schedule create 6751aadb2a37a95edbc90a58 2024-12-12T15:30:00+02:00`
please no CRON_EXP here so it will run once

and about `/poll schedule list_all`
this command only list active "schedule" not poll it self

**Comment by jvdmeij** [comment]
Ah right, i totally missed the `5` in the `CRON_EXP` there. Thanks for this!
